### ISSUE TITLE
No map displayed

### ISSUE THREAD

**Issue by magma1447** [pkozul/ha-floorplan#33]
I am deeply sorry to have to bother others, but I have spent hours rechecking my configuration and Googling to understand the custom-ui's of HASS. Still I have no luck.

My "state card" has the circle icon, nothing more. Definitely no map.
Nothing of interesting in the developer's console, or in HASS's logs.

If I enable the custom panel I just get a loading animation for that panel.
I do get a 404 for the CSS in the developer's console though. But I can not figure out why.
EDIT: This actually works now, not sure what I did or why. I would prefer the state card though, which still doesn't work.

The relevant parts of my configs are available in this pastebin, so is the relevant directory listings.
https://pastebin.com/ZHU8SgJX
All files are readable by the user homeassistant.
It's not very well described where to put those files from git, but as I understand it, it should be in the configuration directory, and this is where my yaml files are stored, as shown in the paste.

My HASS is installed according to https://home-assistant.io/docs/installation/virtualenv/

**Comment by zs85627721** [comment]
got the same issue.

**Comment by pkozul** [comment]
Can you guys try the latest changes, and see if the state card works now? Here are the 3 files that were changed today (last one was added):

customize.yaml
configuration.yaml
frontend.html

**Comment by rpeders** [comment]
same here. panel card works but not the "sensor" one. just shows as a sensor

**Comment by wkonkel** [comment]
Try adding the sensor to a group and then the group to a view:
```
default_view:
  view: yes
  icon: mdi:home
  entities:
    - group.floorplan

floorplan:
  name: Upstairs
  entities:
    - binary_sensor.floorplan
```

**Comment by magma1447** [comment]
Did not solve anything for me.

**Comment by ghost** [comment]
@magma1447, which browser are you using?
For me, it's nothing in Firefox (v57), just panel in Chrome (v62).

**Comment by psamim** [comment]
I have the same problem, Chrome is fine but nothing in Firefox v59.

**Comment by ways** [comment]
Same. No map in FF59. Can see it in chromium.

The state card doesn't work at all.

**Comment by magma1447** [comment]
Today I realized I can get it to work in Firefox (v59.0.2) by using the following group config (group/floorplan.yaml).
```
map:
  name: Map
  entities:
    - binary_sensor.floorplan

Floorplan:
  name: Floorplan
  view: yes
  entities:
    - group.map
````

Chrome (v65.0.3325.181) then shows an empty entity called Map instead of the round binary sensor circle. Still no map though, not even when clicking the entity. Neither does it work in Chrome for Android.
