### ISSUE TITLE
How would i toggle a group all-off/all-on?

### ISSUE THREAD

**Issue by RaZer0r** [pkozul/ha-floorplan#52]
At the moment i have a bunch of lights in one room, which is the group.

```
      groups:
        - name: Lights
          entities:
             - light.tafel
             - light.staanlamp
             - light.bureau
             - light.plafond
             - light.ganglicht
          states:
            - state: 'on'
              class: 'light-on'
            - state: 'off'
              class: 'light-off'
          action:
            domain: homeassistant   # This optional parameter allows you to use other services such as homeassistant.toggle like here.
            service: toggle
        - name: Rooms
          entities:
            - group.lightgroup_living
            - group.lightgroup_eetkamer
            - group.lightgroup_gang
          states:
            - state: 'on'
              class: 'room-on'
            - state: 'off'
              class: 'room-off'
          action:
            domain: homeassistant
            service: toggle
```

When 1 light is on and one light is off in a group, when using toggle --> the one goes off and the other will turn on.
with service: turn_off it only turns off.

How can it be turned on/off?
