### ISSUE TITLE
Script action doesn't work in element group

### ISSUE THREAD

**Issue by natabat** [pkozul/ha-floorplan#53]
This yaml:
```
- name: Garage Toggles
  elements:
    - garage_label
    - garage_area
  action:
    domain: script
    service: toggle_garage_door
```

results in this error:
Uncaught TypeError: Cannot read property 'elements' of undefined
URL: http://192.168.1.8:8123/local/custom_ui/floorplan/ha-floorplan.html
Line: 241, column: 46
Error: {}

The fix is pretty simple -- just add another check to the if statement on that line so it becomes:
`if (elementGroup.action.data && elementGroup.action.data.elements) {`
