### ISSUE TITLE
Floorplan actions are not clickable

### ISSUE THREAD

**Issue by tringler** [pkozul/ha-floorplan#57]
Hello,

I am unable to click to the most icons/actions on my floorplan - Any hints about that behaviour?

Lights config:
```
groups:
  - name: lights
    entities:
      - light.livingroom_ceilinglight
      - light.bedroom_ceilinglight
      - light.bathroom_ceilinglight
      - light.childrenroom_ceilinglight
      - light.kitchen_ceilinglight
      - light.wc_ceilinglight
      - light.kitchen_led
      - light.gateway_light_286c0788b78a
      - light.bedroom_bedsidelamp_tom
      - light.bedroom_bedsidelamp_judith
      - light.balkony
    states:
      - state: 'on'
        class: 'light-on'
      - state: 'off'
        class: 'light-off'
    action:
      domain: light
service: toggle
```

Windows-config:
```
  - name: windows
    entities:
      - binary_sensor.livingroom_climate_windowshutter
      - binary_sensor.bedroom_climate_windowshutter
      - binary_sensor.childrenroom_climate_windowshutter
      - binary_sensor.wc_climate_windowshutter
      - binary_sensor.kitchen_climate_windowshutter
      - binary_sensor.frontdoor_windowshutter
    states:
      - state: 'on'
        class: 'window-on'
      - state: 'off'
class: 'window-off'
```

In examples all lights are not clickable - Example of a light:
```
    <g
       style="display:inline;fill:#808080"
       id="light.bathroom_ceilinglight"
       transform="matrix(0.43596735,0,0,0.43596735,341.66152,-137.02364)"
       inkscape:label="">
```

All windows are hoverable/clickable (they have no actions):
```
    <g
       transform="matrix(0.26449636,0,0,0.28324627,-2452.0094,2059.0055)"
       style="display:inline"
       id="binary_sensor.kitchen_climate_windowshutter"
       inkscape:label="">
```

The states seems to be working without any issues on the floorplan.

Thankful for every hint!
