### ISSUE TITLE
state_transitions are not optional as documented

### ISSUE THREAD

**Issue by oblogic7** [pkozul/ha-floorplan#7]
Documentation states that state_transitions are optional, but in my testing, they do not appear to be.  When that section of the config is omitted, the transition does not happen at all.  Additionally, setting a transition time of 0 does not result in an instant transition.

**Comment by pkozul** [comment]
Cannot reproduce. Tried with the entire `state_transitions` section removed (commented out) and the floorplan displays the colour changes immediately as the sensors are triggered (as expected).

```
        - name: Binary sensors
          entities:
            - binary_sensor.front_hallway
            - binary_sensor.kitchen
            - binary_sensor.master_bedroom
          states:
            - state: 'off'
              class: 'info-background'
            - state: 'on'
              class: 'warning-background'
#          state_transitions:
#            - name: On to off
#              from_state: 'on'
#              to_state: 'off'
#              duration: 10
```

Also tried with `state_transitions` enabled and with a duration of 0, and once again, the floorplan displays the colour changes immediately as the sensors are triggered (as expected).

```
        - name: Binary sensors
          entities:
            - binary_sensor.front_hallway
            - binary_sensor.kitchen
            - binary_sensor.master_bedroom
          states:
            - state: 'off'
              class: 'info-background'
            - state: 'on'
              class: 'warning-background'
          state_transitions:
            - name: On to off
              from_state: 'on'
              to_state: 'off'
              duration: 0
```

Can you try this again?
