### ISSUE TITLE
Multiple floorplan problem

### ISSUE THREAD

**Issue by x2bf3** [pkozul/ha-floorplan#78]
Dear all,

I use many floorplan tab with HAAS named "floorplan" and "groundfloor".

After a visualization of the first floorplan, there is a bug to display the second.
I need to refreNothing apear and I need to use CTRL+F5 to have a result.

**System log :**
Log Details (ERROR)
_Fri Nov 02 2018 17:56:37 GMT+0100 (heure normale d’Europe centrale)_
http://192.168.1.9:8123/api/panel_custom/groundfloor:42:9 Uncaught SyntaxError: Identifier 'HaPanelFloorplan' has already been declared

My configuration :

**/config/configuration.yaml**
```
# Enables the frontend
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-floorplan.html

binary_sensor:
  - platform: mqtt
    state_topic: dummy/floorplan/sensor
    name: Floorplan
  - platform: mqtt
    state_topic: dummy/floorplan/sensor
    name: Groundfloor 
```

**/config/groups.yaml**

 ```
floorplan:
    - name: Floorplan
      entities:
      - binary_sensor.floorplan
      - binary_sensor.groundfloor
```

**/config/panel_custom.yaml**
```

  - name: floorplan
    sidebar_title: Rez-de-chaussée
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml
    
  - name: groundfloor
    sidebar_title: Sous-sol
    sidebar_icon: mdi:home
    url_path: groundfloor
    config: !include groundfloor.yaml
```

Could you please help me to solve this bug ?
Thx by advance.
Nicolas
